#!/bin/bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
project_dir="$( cd "${script_dir}/.." && pwd)"

docker volume create workspace
docker run --rm -t \
    --mount source=workspace,target=/workspace \
    --mount type=bind,source=${project_dir},target=/source,readonly \
    -w /workspace \
    -e BUILD_DIR='/workspace' \
    raphaelmeyer/arch-clang-ninja:1.1.0 /source/scripts/build
